### ISSUE TITLE
VLOOKUP parsing indentation errors?

### ISSUE THREAD

**Issue by simondorfman** [josh3ennett/excelFormulaUtilitiesJS#26]
Hello,
When I paste this formula:
=IF(EXACT(A1,VLOOKUP(A1,Sheet1!A:A,1,FALSE))=TRUE,VLOOKUP(A1,Sheet1!A:A,1,FALSE),"No exact match")

...into http://excelformulabeautifier.com/, the resulting "FALSE"s have no indentation. And the "= TRUE" seems weird.

What do you think?

Thanks,
Simon

**Comment by josh3ennett** [comment]
Sorry, been busy over the past year.  Turns out this is an issue with TRUE and FALSE.  I seem the same behavior on =IF(True,TRUE,FALSE) as well.  Looking into this now.

**Comment by josh3ennett** [comment]
This has been resolved.
