### ISSUE TITLE
Beautify strips apostrophes 

### ISSUE THREAD

**Issue by HorizonsoftDaniel** [josh3ennett/excelFormulaUtilitiesJS#28]
Beautifier turns 'Data Sheet'!$D3 to DataSheet!$D3 breaking links to other sheets. 
<img width="1173" alt="screen shot 2015-09-11 at 22 59 38" src="https://cloud.githubusercontent.com/assets/8768709/9827304/e61d11c8-58d8-11e5-917a-cf70edd7da0c.png">

**Comment by josh3ennett** [comment]
I'm working on this.  I'm making some breaking changes to fix this so may take a few days as I get time. Thanks for the feedback!

**Comment by josh3ennett** [comment]
@HorizonsoftDaniel This has been fixed. give it a try if you get a chance.

**Comment by HorizonsoftDaniel** [comment]
That looks like its got it! Great work :+1:
