### ISSUE TITLE
Remove forced linebreaks

### ISSUE THREAD

**Issue by HLinde** [josh3ennett/excelFormulaUtilitiesJS#29]
Could you remove the forced line-break on http://excelformulabeautifier.com/ after ~140 chars?
I got some very nasty formulas and to me it seems a bit arbitrary to do additional line-breaks with no functional meaning.

Otherwise a very nice tool, helps a lot.
Thanks,
Hannes

**Comment by josh3ennett** [comment]
Thanks for the feedback!  I'll look into this shortly.

**Comment by josh3ennett** [comment]
@HLinde ,  I fixed this using a simple css change.  Take a look and let me know if it works for you.

I tested using this formula:

=IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, IF(SUM( IF(FOO = BAR, 10, 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR"), 0), 10 ) = 20 , "FOO", "BAR")

**Comment by HLinde** [comment]
Very nice, works for me.
Thanks a lot.
