### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by blittle** [josh3ennett/excelFormulaUtilitiesJS#31]
Now that https://github.com/josh3ennett/excelFormulaUtilitiesJS/pull/13 is merged, could you publish this lib to npm?

**Comment by josh3ennett** [comment]
Sounds like a good idea to me.  I've not published anything to npm yet, I'm not sure if there are any other special considerations but i'll check into it.

**Comment by blittle** [comment]
Should be easy, just create a user on npm, and run `npm publish`

**Comment by josh3ennett** [comment]
Yup, that was easy https://www.npmjs.com/package/excel-formula.  Thanks for the push :+1:

**Comment by blittle** [comment]
Nice! thanks!
